### ISSUE TITLE
 Question for Downloading Data Beyond the 1000-Record Limit

### ISSUE THREAD

**Issue by tdrivas** [Agri-Hub/eoProcessors#69]
I’ve noticed that requests to the API have a predefined parameter of maximum record limit of 1000. I’m curious about the behavior when more data needs to be downloaded. Does the application handle pagination or batching automatically to retrieve records beyond the 1000-record limit? If not, we must not use the given function for download but recover the old one, that creates multiple requests until it retrieves the full list of products found.

**Comment by fbalaban** [comment]
This limit is for per response limit. It does not limit the results, meaning that the results will come in batches of 1000, paginated of course. The downloader downloads everything that exists
